apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dotnet-deploy
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dotnet-hello-xltv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dotnet-hello-xltv
    app.kubernetes.io/part-of: my-app-dotnet
  name: dotnet-hello-xltv
  namespace: eyuen-tenant
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  - port: 8080
    targetPort: 8080
  selector:
    app: devfile-dotnet-deploy
    app.kubernetes.io/instance: dotnet-hello-xltv
  type: LoadBalancer
status:
  loadBalancer: {}
