apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: my-app-dotnet
    appstudio.openshift.io/component: dotnet-hello-xltv
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: dotnet-hello-xltv
  namespace: eyuen-tenant
spec:
  url: https://github.com/burrsutter/dotnet-hello
